### ISSUE TITLE
Extract NIST machine-readable PubID from metanorma-nist

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#1]
* Originally implemented as part of https://github.com/metanorma/metanorma-nist/issues/88
* https://github.com/metanorma/metanorma-nist/search?q=nist-mr

The original ticket contents should become part of the README of this gem.

This gem is supposed to do the following:
* Ability to parse a NIST document identifier:
```ruby
NistPubid.parse("NIST SP 800-53r5") #=> NistPubid <instance>
NistPubid.new(publisher: :nist, series: "SP", docnumber: "800-53", revision: 5) #=> NistPubid <instance>
```

* Ability to generate the NIST PubID string outputs
```ruby
NistPubid.parse("NIST SP 800-53r5").to_s(:long)
NistPubid.parse("NIST SP 800-53r5").to_s(:abbrev)
NistPubid.parse("NIST SP 800-53r5").to_s(:short)
```

* parse/convert a NIST PubID into a NIST MR PubID
```ruby
NistPubid.parse("NIST SP 800-53r5").to_s(:mr)
```

* parse/convert a NIST MR PubID into a human readable identifier
```ruby
NistPubid.parse("NIST.SP.800-53.rev5").to_s(:long)
```

* do things with the PubID object, e.g. generate DOI, parse old-style DOI
```ruby
NistPubid.parse_doi("NIST.SP.800-53r5").to_s(:mr)
NistPubid.parse("NIST.SP.800-53.rev5").to_s(:doi)
```

* access/manipulate the PubID object (e.g. get edition, revision, etc)
```ruby
NistPubid.parse("NIST SP 800-53r5").publisher #=> :nist
x = NistPubid.parse("NIST SP 800-53r5")
x.revision = 6
x.revision # => 6
```

This gem will be used by relaton-nist and metanorma-nist.

**Comment by ronaldtse** [comment]
@opoudjis says he can point out the code.

**Comment by opoudjis** [comment]
OK, I don't have code doing a conversion between them. What I have is code that generates both the MR identifier and the PubID identifier from the same source, namely asciidoctor document attributes, and that can be used to produce the mapping:

https://github.com/metanorma/metanorma-nist/blob/main/lib/asciidoctor/nist/front_id.rb

These are the asciidoctor document attributes, converted into a single object:

````
      def id_args(node, dn0)
        return nil unless dn0
        {
          id: dn0,
          series: node.attr("series"),
          subseries: node.attr("series-title") || node.attr("series-abbrev"),
          subseries_abbr: node.attr("series-abbrev"),
          subseries_mr: node.attr("series-mrprefix") || node.attr("series-abbrev"),
          edition: node.attr("edition"),
          version: node.attr("version"),
          revision: node.attr("revision"),
          update: node.attr("update"),
          year: (node.attr("copyright-year") || node.attr("updated-date") ||
                 node.attr("revdate") || node.attr("circulated-date") || 
                 Date.today.year.to_s).sub(/^(....).*$/, "\\1"),
          vol: node.attr("volume"),
          part: node.attr("part") || node.attr("part-number"),
          section: node.attr("section") || node.attr("section-number"),
          supplement: node.attr("supplement") || node.attr("supplement-number"),
          index: node.attr("index") || node.attr("index-number"),
          stage: node.attr("status") || node.attr("docstage"),
          iter: node.attr("iteration"),
          language: node.attr("language") || "en",
          date: /^draft/.match(node.attr("status") || node.attr("docstage")) ?
          (node.attr("circulated-date") || node.attr("revdate")) :
          node.attr("updated-date")
        }
      end
````

This takes the foregoing, and generates the three document identifiers: PubID, Longform PubID, and MR ID:

````
      def metadata_id_compose(node, xml, dn0, did)
        if did
          xml.docidentifier did, **attr_code(type: "NIST")
          xml.docidentifier unabbreviate(did), **attr_code(type: "nist-long")
        else
          args = id_args(node, dn0) || return
          xml.docidentifier add_id_parts(args, false), **attr_code(type: "NIST")
          xml.docidentifier add_id_parts(args, true), **attr_code(type: "nist-long")
          xml.docidentifier add_id_parts_mr(args), **attr_code(type: "nist-mr")
        end
      end
````

This is the document PubID

````
      def add_id_parts(args, long)
        args[:series] and series_name = id_series_name(args, (long ? :long : :short))
        dn = (series_name || "NIST #{args[:series]}")  + " " + args[:id]
        dn += " Volume #{args[:vol]}" if args[:vol]
        dn += "," if args[:vol] && args[:revision]
        dn += " Revision #{args[:revision]}" if args[:revision]
        dn += "/Upd #{args[:update]}:#{args[:year]}" if args[:update]
        stage = status_abbr(args[:stage], args[:iter]) and dn += " (#{stage})"
        dn += " (#{MMMddyyyy(args[:date])})" if args[:date]
        dn
      end
````

and this is the MR ID:

````
      def id_parts_mr(args)
        part = []
        part << "v-#{args[:vol]}" if args[:vol]
        part << "pt-#{args[:part]}" if args[:part]
        part << "sec-#{args[:section]}" if args[:section]
        part << "sup-#{args[:supplement]}" if args[:supplement]
        part << "indx-#{args[:index]}" if args[:index]
        part
      end

      def id_editions_mr(args)
        part = []
        part << "e-#{args[:edition]}" if args[:edition]
        part << "r-#{args[:revision]}" if args[:revision]
        part << "ver-#{args[:version]}" if args[:version]
        part
      end

      def id_lang_mr(args)
        ret = args[:language].split(/,\s*/).map do |l|
          ISO_639.find(l).alpha3
        end.join(",")
      end

      def add_id_parts_mr(args)
        ret = ["NIST"]
        args[:series] and ret << id_series_name(args, :mr)&.sub(/^NIST /, "")
        stage = status_abbr(args[:stage], nil) || ""
        stage += "[-#{args[:iter]}]" if args[:iter]
        ret << stage unless stage.empty?
        ret << args[:id]
        ret += id_parts_mr(args)
        ret += id_editions_mr(args)
        ret << id_lang_mr(args)
        args[:update] and ret << "upd-#{args[:update]}:#{args[:year]}"
        ret.join(".")
      end
````

**Comment by andrew2net** [comment]
@ronaldtse the code above doesn't contain DOI to PubId conversion rules. We need the rules to implement this gem.

**Comment by ronaldtse** [comment]
@andrew2net for DOI to NIST PubID you will need to infer the rules from the existing database. You will a few different patterns because previously they were not set consistently. 

The point is that in the future it will be consistent according to the NIST MR scheme linked from the ticket.

**Comment by andrew2net** [comment]
@ronaldtse the MR ID format has `sup` (supplement) but I'm unable to find how a supplement should be displayed in PubID. Can you ask NIST for clarification?

**Comment by ronaldtse** [comment]
@andrew2net can you provide the full example in a separate issue?

Yes, NIST does have a "Supplement" and also the Addendum (https://github.com/metanorma/metanorma-nist/issues/259).

"Supplement" is a numbered attribute like Addendum:
* "Supplement 1" is just called "Supplement"
* "Supplement 2" is just called "Supplement 2"

Examples:
* https://nistdigitalarchives.contentdm.oclc.org/digital/collection/p15421coll1/id/8075
* https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication305supp22.pdf
* https://books.google.com.hk/books?id=cWcEAQAAIAAJ&dq=nist+special+publication+supplement+-172

Representation: e.g.
<img width="664" alt="Screenshot 2021-07-22 at 9 45 04 PM" src="https://user-images.githubusercontent.com/11865/126649446-93f30cda-76db-4dc6-b780-4622a196238d.png">

<img width="407" alt="Screenshot 2021-07-22 at 9 48 09 PM" src="https://user-images.githubusercontent.com/11865/126649912-09aa7ca5-b410-4160-a630-a2cc09bb972e.png">

<img width="502" alt="Screenshot 2021-07-22 at 9 48 25 PM" src="https://user-images.githubusercontent.com/11865/126649959-c4c8e9bf-986f-44c6-b4a3-54080138b964.png">

In PubID, the "Supplement":
* short: "Suppl. X"
* long: "Supplement X"

**Comment by ronaldtse** [comment]
The relevant code is here: https://github.com/relaton/relaton-nist/blob/master/lib/relaton_nist/nist_bibliography.rb

**Comment by ronaldtse** [comment]
@mico can you help create a PR that implements the NIST PubID from your work here? Thanks!

**Comment by mico** [comment]
@ronaldtse I need more data to parse and convert from/to DOI format, I found only one example here:
```
NistPubid.parse_doi("NIST.SP.800-53r5").to_s(:mr)
NistPubid.parse("NIST.SP.800-53.rev5").to_s(:doi)

```

**Comment by mico** [comment]
@ronaldtse also I need more data for Section, Supplement, Index, Insert, Errata. Examples and more details.

**Comment by ronaldtse** [comment]
> I need more data for Section, Supplement, Index, Insert, Errata. Examples and more details.

That is filed as #8. Let's close this task for now.
