### ISSUE TITLE
Parse missing update data for some identifiers

### ISSUE THREAD

**Issue by mico** [metanorma/nist-pubid#106]
NIST AMS 300-8r1 (February 2021 update), NISTIR 8115r1/upd - missing update

_Originally posted by @mico in https://github.com/metanorma/nist-pubid/issues/94#issuecomment-1017157085_

**Comment by mico** [comment]
@ronaldtse I'm struggling with "NIST AMS 300-8r1 (February 2021 update)" what it can be in result? We don't have month in proposal, only update number:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/5849/150735746-f34e59a0-9af6-439e-b367-7d26ff0fcc7d.png">
<img width="859" alt="image" src="https://user-images.githubusercontent.com/5849/150735767-f9ec8489-606c-4310-aa0b-a499879807f1.png">
<img width="275" alt="image" src="https://user-images.githubusercontent.com/5849/150735798-98825aa8-7248-4619-892a-29be489530ee.png">
Can it be "NIST AMS 300-8r1/Upd2-2021" ? ("2" because of second month, February)

**Comment by ronaldtse** [comment]
@mico `NIST AMS 300-8r1/Upd{N}-{YYYY}` the N is always the sequence number of the update and YYYY the date. In this case I would say we do `NIST AMS 300-8r1/Upd1-202102` (where YYYY is now YYYYMM).

**Comment by mico** [comment]
> Also, I see there is a requirement to have "update year", so can't use just "NISTIR 8115r1/Upd1" for "NISTIR 8115r1/upd"

@ronaldtse what do you think about this? We don't have update year for "NISTIR 8115r1/upd"
There is also other identifiers without year in update, examples:
- NISTIR 8115r1-upd
- NIST SP 500-300-upd
- NISTIR 8170-upd

**Comment by ronaldtse** [comment]
If possible we want to have the update year for those documents. Can we obtain them from the XML file?

**Comment by mico** [comment]
> If possible we want to have the update year for those documents. Can we obtain them from the XML file?

There are only 4 documents with update without year, we can add a year to parser for every identifier.
- NISTIR 8115r1/upd
- NISTIR 8115r1-upd
- NIST SP 500-300-upd
- NISTIR 8170-upd
- NIST TN 2150-upd

**Comment by ronaldtse** [comment]
@mico sounds fine, thanks!
