### ISSUE TITLE
Accept "1-2_3-1" as part of docnumber for NBS CRPL series

### ISSUE THREAD

**Issue by mico** [metanorma/nist-pubid#107]
NBS CRPL 1-2_3-1 - should we accept 1-2_3-1 as acceptable document number?
The same for "NBS CRPL 1-2_3-1A".

_Originally posted by @mico in https://github.com/metanorma/nist-pubid/issues/94#issuecomment-1017157085_

**Comment by ronaldtse** [comment]
## NBS CRPL 1-2, 3,1

https://nvlpubs.nist.gov/nistpubs/Legacy/crpl/crpl-1-2_3-1.pdf
<img width="1225" alt="Screenshot 2022-01-21 at 12 35 41 AM" src="https://user-images.githubusercontent.com/11865/150381673-69d5572f-b054-47a3-a962-e0a61cb18da5.png">
<img width="1177" alt="Screenshot 2022-01-21 at 12 35 53 AM" src="https://user-images.githubusercontent.com/11865/150381701-14d10004-88ac-4720-8ee5-59d2298d4285.png">

The document number is really "NBS CRPL 1-2, 3-1". I think this means "NBS CRPL 1-2", Part "3-1".

## "NBS CRPL 1-2_3-1A":

https://nvlpubs.nist.gov/nistpubs/Legacy/crpl/crpl-1-2_3-1A.pdf
<img width="1251" alt="Screenshot 2022-01-21 at 12 31 10 AM" src="https://user-images.githubusercontent.com/11865/150380858-50aab690-820b-4f53-a101-77bc4ec65f90.png">
<img width="1052" alt="Screenshot 2022-01-21 at 12 31 16 AM" src="https://user-images.githubusercontent.com/11865/150380895-0fe7c739-0734-4365-af41-60ee26baa139.png">
<img width="1217" alt="Screenshot 2022-01-21 at 12 31 28 AM" src="https://user-images.githubusercontent.com/11865/150380929-bb71b8d0-e591-4ada-917b-8feeccdf07ea.png">

The document number is "NBS CRPL 1-2, 3-1, A", which "A" here stands for "Supplement".

**Comment by mico** [comment]
> The document number is really "NBS CRPL 1-2, 3-1". I think this means "NBS CRPL 1-2", Part "3-1".

Should it be something lile "NBS CRPL 1-2pt3-1" in result?

> The document number is "NBS CRPL 1-2, 3-1, A", which "A" here stands for "Supplement".

Should it become something like "NBS CRPL 1-2pt3-1supA" ?

**Comment by ronaldtse** [comment]
@mico "NBS CRPL 1-2pt3-1supA" is for MR?

How about the following?
* MR: `NBS.CRPL.1-2pt3-1supA`
* Short: `NBS CRPL 1-2 Pt. 3-1 Suppl. A`

**Comment by mico** [comment]
> * Short: `NBS CRPL 1-2 Pt. 3-1 Suppl. A`

I thought we use Pt. and Suppl. for abbreviated PubID, that's how it works now.

**Comment by ronaldtse** [comment]
That’s not what it says here: https://github.com/metanorma/nist-pubid#part

**Comment by ronaldtse** [comment]
Or not?

**Comment by mico** [comment]
> According to the README we use the same “Part” phrases for abbrev and short: https://github.com/metanorma/nist-pubid#part

I was using examples in NIST PubID proposal as reference:

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/5849/150486999-83ed675b-8818-4305-ad8b-036c8c7fcaf7.png">
But there is nothing about abbreviated and long PubID

**Comment by ronaldtse** [comment]
Ah, you're right. Then we should update our README.
