### ISSUE TITLE
Rewrite parsing to use parslet

### ISSUE THREAD

**Issue by mico** [metanorma/nist-pubid#141]
Implement data elements and patterns as classes.
@ronaldtse should I rewrite everything or we can start with most sensitive parts and leave not critical ones for the future?

**Comment by ronaldtse** [comment]
Let's start with the most sensitive parts and then start refactoring the whole logic. We will re-use similar logic and architecture for other PubID gems.

**Comment by ronaldtse** [comment]
In addition, I think we should define a generic mechanism for people to define PubIDs.

**Comment by mico** [comment]
> In addition, I think we should define a generic mechanism for people to define PubIDs.

Could you give an example?

**Comment by ronaldtse** [comment]
@mico we also need to do PubIDs for IEEE, ISO, IEC etc. These schemes need also to be encoded, and I'd rather they be some declared pattern instead of an implementation in code.

**Comment by ronaldtse** [comment]
Closing for #143.
