### ISSUE TITLE
(URGENT) FIPS PUB losing date of publication/edition

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#46]
PubID | Original
-- | --
NBS FIPS PUB 1-2 | NBS FIPS 1-2-1974
NBS FIPS PUB 1-2 | NBS FIPS 1-2-1977
NBS FIPS PUB 1-2 | NBS FIPS 1-2-1984

These are documents of different editions. We lost the identification here.

**Comment by ronaldtse** [comment]
Same here:

PubID | Original
-- | --
NBS FIPS PUB 14-1971 | NBS FIPS 14-1971
NBS FIPS PUB 14-1 | NBS FIPS 14-1-Dec1980
NBS FIPS PUB 14-1 | NBS FIPS 14-1-May1980

**Comment by mico** [comment]
@ronaldtse I cannot find examples what NBS FIPS 14-1-Dec1980 should become.
"NBS FIPS PUB 14-1eDec1980" looks strange.
