### ISSUE TITLE
(URGENT) FIPS PUBS MR scheme wrong (`NIST.FIPS` not `NIST.FIPS.PUB`)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#47]
See https://github.com/metanorma/nist-pubid/blob/main/README.adoc
<img width="551" alt="Screenshot 2022-01-10 at 3 33 04 PM" src="https://user-images.githubusercontent.com/11865/148731299-46586e09-72b7-4c76-8aef-7d69ec162ed9.png">

See these:

MR | DOI
-- | --
NBS.FIPS.PUB.34 | NBS.FIPS.34
NBS.FIPS.PUB.35 | NBS.FIPS.35
NBS.FIPS.PUB.36 | NBS.FIPS.36
NBS.FIPS.PUB.36-1975 | NBS.FIPS.36-1975

**Comment by mico** [comment]
@ronaldtse we have FIPS PUB from NIST and NBS (examples: `NIST FIPS 100-1` and `NBS FIPS 101`)
Should it be NIST.FIPS.100-1 and NBS.FIPS.101 as a result of conversion? Is it the same for Final PubID?

**Comment by ronaldtse** [comment]
> Should it be NIST.FIPS.100-1 and NBS.FIPS.101 as a result of conversion? Is it the same for Final PubID?

Yes I believe so.
