### ISSUE TITLE
(URGENT) NBS FIPS PUB month recognition failure

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#48]
PubID | Original
-- | --
NBS FIPS PUB 33-MA | NBS FIPS 33-May1974
NBS FIPS PUB 33-OC | NBS FIPS 33-Oct1974
NBS FIPS PUB 82-SE | NBS FIPS 82-Sep1980
NBS FIPS PUB 85-MA | NBS FIPS 85-May1980
NBS FIPS PUB 85-NOv1980 | NBS FIPS 85-Nov1980
NBS FIPS PUB 89-MA | NBS FIPS 89-May1981
NBS FIPS PUB 89-SE | NBS FIPS 89-Sep1981
NBS FIPS PUB 90-JU | NBS FIPS 90-Jul1983
NBS FIPS PUB 90-SE | NBS FIPS 90-Sep1983

**Comment by ronaldtse** [comment]
Another set of broken parses:

PubID | Original
-- | --
NBS FIPS PUB 70-1 | NBS FIPS 70-1-Jun1986
NBS FIPS PUB 70-1v1986 | NBS FIPS 70-1-Nov1986

**Comment by ronaldtse** [comment]
More.

PubID | Original | (ignore) | MR | DOI
NIST FIPS PUB 54-1 | NIST FIPS 54-1-Jan15 | TRUE | NIST.FIPS.PUB.54-1 | NIST.FIPS.54-1-Jan15/1991
NIST FIPS PUB 54-1 | NIST FIPS 54-1-Jan17 | TRUE | NIST.FIPS.PUB.54-1 | NIST.FIPS.54-1-Jan17/1991

**Comment by mico** [comment]
@ronaldtse could you give any examples what it should be in result? Cannot find any with a month included.
