### ISSUE TITLE
(URGENT) "NIST IR 6806rNNNN", the "NNNN" is edition not part

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#51]
NIST IR 6806-2002 | NIST IR 6806r2002
-- | --
NIST IR 6806-2004 | NIST IR 6806r2004

**Comment by ronaldtse** [comment]
Also this:

PubID | Original ID | (ignore) | MR | DOI
-- | -- | -- | -- | --
NIST IR 8118-1 | NIST IR 8118r1 | TRUE | NIST.IR.8118-1 | NIST.IR.8118r1
NIST SP 1026-1 | NIST SP 1026r1 | TRUE | NIST.SP.1026-1 | NIST.SP.1026r1
NIST SP 1026-2009 | NIST SP 1026r2009 | TRUE | NIST.SP.1026-2009 | NIST.SP.1026r2009
NIST SP 1041-1 | NIST SP 1041r1 | TRUE | NIST.SP.1041-1 | NIST.SP.1041r1
NIST SP 1086-1 | NIST SP 1086r1 | TRUE | NIST.SP.1086-1 | NIST.SP.1086r1
NIST SP 1108-2 | NIST SP 1108r2 | TRUE | NIST.SP.1108-2 | NIST.SP.1108r2
NIST SP 1108-3 | NIST SP 1108r3 | TRUE | NIST.SP.1108-3 | NIST.SP.1108r3
NIST SP 1200-5-1 | NIST SP 1200-5r1 | TRUE | NIST.SP.1200-5-1 | NIST.SP.1200-5r1
NIST SP 1500-100-2 | NIST SP 1500-100r2 | TRUE | NIST.SP.1500-100-2 | NIST.SP.1500-100r2
NIST SP 1500-10-1 | NIST SP 1500-10r1 | TRUE | NIST.SP.1500-10-1 | NIST.SP.1500-10r1
NIST SP 1500-1-1 | NIST SP 1500-1r1 | TRUE | NIST.SP.1500-1-1 | NIST.SP.1500-1r1
NIST SP 1500-1-2 | NIST SP 1500-1r2 | TRUE | NIST.SP.1500-1-2 | NIST.SP.1500-1r2
NIST SP 1500-2-1 | NIST SP 1500-2r1 | TRUE | NIST.SP.1500-2-1 | NIST.SP.1500-2r1
NIST SP 1500-2-2 | NIST SP 1500-2r2 | TRUE | NIST.SP.1500-2-2 | NIST.SP.1500-2r2
NIST SP 1500-3-1 | NIST SP 1500-3r1 | TRUE | NIST.SP.1500-3-1 | NIST.SP.1500-3r1
NIST SP 1500-3-2 | NIST SP 1500-3r2 | TRUE | NIST.SP.1500-3-2 | NIST.SP.1500-3r2
NIST SP 1500-4-1 | NIST SP 1500-4r1 | TRUE | NIST.SP.1500-4-1 | NIST.SP.1500-4r1
NIST SP 1500-4-2 | NIST SP 1500-4r2 | TRUE | NIST.SP.1500-4-2 | NIST.SP.1500-4r2
NIST SP 1500-6-1 | NIST SP 1500-6r1 | TRUE | NIST.SP.1500-6-1 | NIST.SP.1500-6r1
NIST SP 1500-6-2 | NIST SP 1500-6r2 | TRUE | NIST.SP.1500-6-2 | NIST.SP.1500-6r2
NIST SP 1500-7-1 | NIST SP 1500-7r1 | TRUE | NIST.SP.1500-7-1 | NIST.SP.1500-7r1
NIST SP 1500-7-2 | NIST SP 1500-7r2 | TRUE | NIST.SP.1500-7-2 | NIST.SP.1500-7r2
NIST SP 1500-9-1 | NIST SP 1500-9r1 | TRUE | NIST.SP.1500-9-1 | NIST.SP.1500-9r1
NIST SP 250-1039-1 | NIST SP 250-1039r1 | TRUE | NIST.SP.250-1039-1 | NIST.SP.250-1039r1

**Comment by ronaldtse** [comment]
And these



NIST SP 800-53-1 | NIST SP 800-53r1 | TRUE | NIST.SP.800-53-1 | NIST.SP.800-53r1
-- | -- | -- | -- | --
NIST SP 800-53-2 | NIST SP 800-53r2 | TRUE | NIST.SP.800-53-2 | NIST.SP.800-53r2
NIST SP 800-53-3 | NIST SP 800-53r3 | TRUE | NIST.SP.800-53-3 | NIST.SP.800-53r3
NIST SP 800-53-4 | NIST SP 800-53r4 | TRUE | NIST.SP.800-53-4 | NIST.SP.800-53r4
NIST SP 800-53-5 | NIST SP 800-53r5 | TRUE | NIST.SP.800-53-5 | NIST.SP.800-53r5
NIST SP 800-55-1 | NIST SP 800-55r1 | TRUE | NIST.SP.800-55-1 | NIST.SP.800-55r1

**Comment by mico** [comment]
fixed in #49, right?

**Comment by ronaldtse** [comment]
Correct.
