### ISSUE TITLE
(URGENT) "NIST SP 801-err" should be "NIST SP 801err"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#53]
NIST SP 801-err | NIST SP 801-errata | TRUE | NIST.SP.801-err | NIST.SP.801-errata
-- | -- | -- | -- | --

According to the rules:
<img width="465" alt="Screenshot 2022-01-10 at 3 57 54 PM" src="https://user-images.githubusercontent.com/11865/148733790-22158044-3804-45cd-9b06-f5b3b43ede6b.png">

**Comment by mico** [comment]
@ronaldtse fixed in #60
