### ISSUE TITLE
Provide review comments for newly published NIST PubID draft document

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#6]
From NIST:

> We have released a news item on NIST.gov that includes a link to our Publication identifier proposal, and a request for comments by September 30. Please share with anyone in your networks that would be interested. And, as always, please let us know if you have any questions.
>
> https://www.nist.gov/news-events/news/2021/08/nist-technical-series-publications-proposed-publication-identifier-syntax
>
> direct link to the proposal: https://www.nist.gov/system/files/documents/2021/08/26/Publication-ID-Proposal_26Aug21.pdf

* @andrew2net can you check if we are missing anything in the nist-pubid gem and Relaton NIST?
* @opoudjis can you review to see if we have any gaps in document IDs right now?
* @strogonoff @wkwong-ribose @ribose-jeffreylau please have a look.

We will need to provide comments by September 30, so please help provide them in this thread for compilation by mid September.

**Comment by opoudjis** [comment]
There is an ambiguity in the handling of report number, p. 7: a volume or edition can be treated as either part of the report number, or as a separate part number or edition number, idiosyncratically depending on the series; that makes the PubID unpredictable. Making the edition type mandatory eliminates this ambiguity, and so would making the part-type mandatory at least in the case of volume.

**Comment by opoudjis** [comment]
We do not currently cater for parts with no part id (e.g. `sup` or `indx` on its own), but that's a straightforward extension: an empty document attribute supplied, rather than a missing one. Will add.

**Comment by opoudjis** [comment]
If the part type is omitted (which I think is a bad idea), we will need to default it to something in NIST MR ID; I would default it to "part". 

If there is no part type, the PubID is going to be unacceptably ambiguous; right now, 1000pt1 without a part type would turn into 10001, with no explicit delimiter foreseen between the report number and the part number.

**Comment by opoudjis** [comment]
NIST MR ID practice has been to use the two-letter ISO-639-2 code for languages; I don't see a compelling reason to use the three-letter code instead, but we can generate it.

**Comment by ronaldtse** [comment]
@opoudjis the 2-letter code does not handle a number of languages, and supporting the 3-letter code makes it also compatible with the other ISO 639 parts. Definitely prefer the 3-letter code.

(That said, amongst the NIST Tech Pub history has only seen translations to Spanish, Vietnamese, Portuguese and Chinese.)

**Comment by ronaldtse** [comment]
> If the part type is omitted (which I think is a bad idea), we will need to default it to something in NIST MR ID; I would default it to "part".

In NIST MR ID we never omit the part, it is always explicit. It would be `part-A` or `part-1` or no part at all.

> The examples of existing PubIDs with no explicit part type get around this by using capital letters; e.g. in NIST SP 800-53Ar4, the A is meant to be recognised as a part, since a capital letter can't be a part of the report number. That also means that an Arabic numeral cannot be used with no part type as a part id.

The arabic numbered parts in traditional NIST document identifiers use hyphens as the separator, e.g. NIST SP 800-35-2. I'm not fully understanding your statement...

**Comment by ronaldtse** [comment]
Thanks @opoudjis for providing the https://github.com/metanorma/metanorma-nist/issues/53 ticket. NIST has originally decided to remove "parts" from the scheme in 2019, but it has officially come back in 2021. So...

**Comment by opoudjis** [comment]
> @opoudjis the 2-letter code does not handle a number of languages, and supporting the 3-letter code makes it also compatible with the other ISO 639 parts. Definitely prefer the 3-letter code.
> 
> (That said, amongst the NIST Tech Pub history has only seen translations to Spanish, Vietnamese, Portuguese and Chinese.)

Three-letter-only languages are not languages NIST is going to be publishing in. (Cherokee? Gilbertese?) But no matter.

**Comment by opoudjis** [comment]
> > If the part type is omitted (which I think is a bad idea), we will need to default it to something in NIST MR ID; I would default it to "part".
> 
> In NIST MR ID we never omit the part, it is always explicit. It would be `part-A` or `part-1` or no part at all.
> 
> > The examples of existing PubIDs with no explicit part type get around this by using capital letters; e.g. in NIST SP 800-53Ar4, the A is meant to be recognised as a part, since a capital letter can't be a part of the report number. That also means that an Arabic numeral cannot be used with no part type as a part id.
> 
> The arabic numbered parts in traditional NIST document identifiers use hyphens as the separator, e.g. NIST SP 800-35-2. I'm not fully understanding your statement...

NIST SP 800-53Ar4 is an existing document identifier. In that document identifier, A is a part number, and it does not have an explicit "part" type, such as "pt". The only way we know that the A is a part number is that it is a letter and not a number. There is NOTHING in the document stating that rule about alphabetic part numbers with no "pt" prefix. That is an oversight.

**Comment by ronaldtse** [comment]
The latest draft also lacks mechanism to generate NIST MR, so we need to contribute that back to NIST.

**Comment by ronaldtse** [comment]
Done in https://github.com/riboseinc/report-nist-pubid.
