### ISSUE TITLE
(URGENT) Broken "NIST SP 800-nn{part}r{x}" when {part} exists

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#69]
PubID | Original
-- | --
NIST SP 800-53A | NIST SP 800-53Ar4
NIST SP 800-56A | NIST SP 800-56a
NIST SP 800-56A | NIST SP 800-56ar
NIST SP 800-56A | NIST SP 800-56Ar2
NIST SP 800-56A | NIST SP 800-56Ar3
NIST SP 800-56B | NIST SP 800-56b
NIST SP 800-56B | NIST SP 800-56Br1
NIST SP 800-56B | NIST SP 800-56Br2
NIST SP 800-56C | NIST SP 800-56c
NIST SP 800-56C | NIST SP 800-56Cr1
NIST SP 800-56C | NIST SP 800-56Cr2

i.e. "NIST SP 800-53Ar4" is correct, it should not be changed into "NIST SP 800-53A".

**Comment by mico** [comment]
It was fixed before, check it again please

**Comment by ronaldtse** [comment]
Confirmed. Thanks!
<img width="347" alt="Screenshot 2022-01-11 at 12 56 41 PM" src="https://user-images.githubusercontent.com/11865/148883702-6ed1afc6-c1bb-4275-b24d-87310862d735.png">
