### ISSUE TITLE
(URGENT) NIST FIPS identifiers with months parsed wrongly

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#72]
Changed? | PubID | Original | Changed? | MR | DOI
-- | -- | -- | -- | -- | --
TRUE | NBS FIPS PUB 107-FE | NBS FIPS 107-Feb1985 | TRUE | NBS.FIPS.PUB.107-FE | NBS.FIPS.107-Feb1985
TRUE | NBS FIPS PUB 107-MAr1985 | NBS FIPS 107-Mar1985 | TRUE | NBS.FIPS.PUB.107-MAr1985 | NBS.FIPS.107-Mar1985
TRUE | NBS FIPS PUB 108 | NBS FIPS 108 | TRUE | NBS.FIPS.PUB.108 | NBS.FIPS.108
TRUE | NBS FIPS PUB 108-1984 | NBS FIPS 108-1984 | TRUE | NBS.FIPS.PUB.108-1984 | NBS.FIPS.108-1984
TRUE | NBS FIPS PUB 109 | NBS FIPS 109 | TRUE | NBS.FIPS.PUB.109 | NBS.FIPS.109
TRUE | NBS FIPS PUB 109-1985 | NBS FIPS 109-1985 | TRUE | NBS.FIPS.PUB.109-1985 | NBS.FIPS.109-1985
TRUE | NBS FIPS PUB 110 | NBS FIPS 110 | TRUE | NBS.FIPS.PUB.110 | NBS.FIPS.110
TRUE | NBS FIPS PUB 111 | NBS FIPS 111 | TRUE | NBS.FIPS.PUB.111 | NBS.FIPS.111
TRUE | NBS FIPS PUB 111-1985 | NBS FIPS 111-1985 | TRUE | NBS.FIPS.PUB.111-1985 | NBS.FIPS.111-1985
TRUE | NBS FIPS PUB 11-1eSep1977 | NBS FIPS 11-1-Sep1977 | TRUE | NBS.FIPS.PUB.11-1eSep1977 | NBS.FIPS.11-1-Sep1977
TRUE | NBS FIPS PUB 11-1eSep30 | NBS FIPS 11-1-Sep30 | TRUE | NBS.FIPS.PUB.11-1eSep30 | NBS.FIPS.11-1-Sep30/1977
TRUE | NBS FIPS PUB 112 | NBS FIPS 112 | TRUE | NBS.FIPS.PUB.112 | NBS.FIPS.112
TRUE | NBS FIPS PUB 113 | NBS FIPS 113 | TRUE | NBS.FIPS.PUB.113 | NBS.FIPS.113
TRUE | NBS FIPS PUB 114-DE | NBS FIPS 114-Dec1985 | TRUE | NBS.FIPS.PUB.114-DE | NBS.FIPS.114-Dec1985
TRUE | NBS FIPS PUB 114-SE | NBS FIPS 114-Sep1985 | TRUE | NBS.FIPS.PUB.114-SE | NBS.FIPS.114-Sep1985
TRUE | NBS FIPS PUB 115-MAr1985 | NBS FIPS 115-Mar1985 | TRUE | NBS.FIPS.PUB.115-MAr1985 | NBS.FIPS.115-Mar1985
TRUE | NBS FIPS PUB 115-SE | NBS FIPS 115-Sep1985 | TRUE | NBS.FIPS.PUB.115-SE | NBS.FIPS.115-Sep1985
TRUE | NBS FIPS PUB 116-A | NBS FIPS 116-Apr1985 | TRUE | NBS.FIPS.PUB.116-A | NBS.FIPS.116-Apr1985
TRUE | NBS FIPS PUB 116-SE | NBS FIPS 116-Sep1985 | TRUE | NBS.FIPS.PUB.116-SE | NBS.FIPS.116-Sep1985

**Comment by mico** [comment]
It was fixed here https://github.com/metanorma/nist-pubid/pull/62
