### ISSUE TITLE
Move commented document identifiers to specs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#9]
https://github.com/metanorma/nist-pubid/blob/14cc82a9c3d910e0416a5d4de887420e19302730/spec/nist_pubid/document_spec.rb#L3-L21

**Comment by mico** [comment]
@ronaldtse done in #11

**Comment by ronaldtse** [comment]
Just to be sure, we want to have all the examples provided in the NIST PubID 2021-08 scheme document in the specs. @mico can you help confirm? If so please help close this. Thanks!

**Comment by ronaldtse** [comment]
All done.
